use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :twitter, Twitter.Endpoint,
  http: [:inet6, port: {:system, "TWITTER_PORT"}],
  url: [host: "localhost", port: {:system, "TWITTER_PORT"}],
  server: true,
  root: ".",
  version: Application.spec(:twitter, :vsn)

config :twitter, Twitter.HTTPClient,
  bearer_token: {:system, "BEARER_TOKEN"},
  screen_name: {:system, "SCREEN_NAME"}
